name: Build and Deploy Documentation

on:
  push:
    branches:
      - master
      - release/* # Default release branch

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: .documentation/docfx.json

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: .documentation/_site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
